---
# yaml-language-server: $schema=https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ems-file-service
  description: Datasets, metadata, and scripts to generate the static assets for EMS File Service

  annotations:
    backstage.io/source-location: url:https://github.com/elastic/ems-file-service/
    github.com/project-slug: elastic/ems-file-service
    github.com/team-slug: elastic/ems
    buildkite.com/project-slug: elastic/ems-file-service

  tags:
    - ems
    - kibana
    - data
  
  links:
    - title: Documentation
      url: https://github.com/elastic/ems-file-service/blob/master/README.md
    - title: EMS License
      url: https://www.elastic.co/elastic-maps-service-terms

spec:
  type: service
  owner: group:ems
  lifecycle: production

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-ems-file-service
  description: Buildkite Pipeline for ems-file-service
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/ems-file-service

spec:
  type: buildkite-pipeline
  owner: group:ems
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: EMS File Service
      description: Pipeline to run the EMS File Service tests suite and deployment
    spec:
      repository: elastic/ems-file-service
      pipeline_file: ".buildkite/pipeline.yml"
      default_branch: master
      env:
        ELASTIC_PR_COMMENTS_ENABLED: 'true'
      teams: # Who has access to the pipeline.
        ems: {}
        everyone:
          access_level: READ_ONLY
      provider_settings:
        publish_commit_status: true

