agents:
  image: "docker.elastic.co/ci-agent-images/ems/buildkite-agent:latest"

steps:
  - key: test
    label: ":hammer_and_wrench: Test and build"
    commands: 
      - "yarn install"
      - "yarn test"
      - "yarn build"
      - "tar cf dist.tar dist"
    artifact_paths: "dist.tar"

  - key: deploy-development
    label: ":rocket: Deploy to the development environment"
    branches: "feature-layers"
    depends_on: test
    command: ".buildkite/deploy.sh"
    env:
      TILE_HOST: "tiles.maps.elastic.co"
      VECTOR_HOST: "storage.googleapis.com/elastic-bekitzur-emsfiles-vector-dev"
      GCS_VAULT_SECRET_PATH: "secret/ci/elastic-ems-file-service/testing/gcs_acount" #TO UPDATE
      CATALOGUE_BUCKET: "elastic-ems-dev-emsfiles-catalogue-dev" #TO UPDATE
      VECTOR_BUCKET: "elastic-ems-dev-emsfiles-vector-dev" #TO UPDATE

  - key: deploy-staging
    label: ":rocket: Deploy to the staging environment"
    branches: "master"
    depends_on: test
    command: ".buildkite/deploy.sh"
    env:
      TILE_HOST: "tiles.maps.elastic.co"
      VECTOR_HOST: "vector-staging.maps.elastic.co"
      GCS_VAULT_SECRET_PATH: "secret/ci/elastic-ems-file-service/testing/gcs_acount" #TO UPDATE
      CATALOGUE_BUCKET: "elastic-ems-dev-emsfiles-catalogue-dev" #TO UPDATE
      VECTOR_BUCKET: "elastic-ems-dev-emsfiles-vector-dev" #TO UPDATE

  - key: should-deploy
    block: ":one-does-not-simply: Deploy to production?"
    #if: "build.tag!=null"
    depends_on: test

  - key: deploy-production
    label: ":rocket: Deploy to the production environment"
    depends_on: should-deploy
    command: ".buildkite/deploy.sh"
    env:
      TILE_HOST: "tiles.maps.elastic.co"
      VECTOR_HOST: "vector.maps.elastic.co"
      GCS_VAULT_SECRET_PATH: "secret/ci/elastic-ems-file-service/testing/gcs_acount" #TO UPDATE
      CATALOGUE_BUCKET: "elastic-ems-dev-emsfiles-catalogue-dev" #TO UPDATE
      VECTOR_BUCKET: "elastic-ems-dev-emsfiles-vector-dev" #TO UPDATE
      ARCHIVE_BUCKET: "elastic-ems-dev-emsfiles-vector-dev" #TO UPDATE
