agents:
  image: "docker.elastic.co/ci-agent-images/ems/buildkite-agent-node22:1763046358@sha256:468e1647968235b38473c576d963fc1581d9b2d363ef949ddfae2b5967bac9fd"
  cpu: "2"
  memory: "2G"

steps:
  - key: test
    label: ":hammer_and_wrench: Test"
    commands:
      - "yarn install"
      - "yarn lint"
      - "yarn test"
    retry:
      automatic: true
    agents:
      cpu: "4"
      memory: "4G"

  - key: deploy-development
    label: ":rocket: Development"
    branches: "feature-layers"
    depends_on: test
    command: ".buildkite/deploy.sh"
    env:
      EMS_ENVIRONMENT: "development"

  - key: deploy-staging
    label: ":rocket: Staging"
    branches: "master"
    depends_on: test
    command: ".buildkite/deploy.sh"
    env:
      EMS_ENVIRONMENT: "staging"

  - key: should-deploy
    block: ":one-does-not-simply: Deploy"
    if: "build.tag!=null"
    depends_on: test

  - key: deploy-production
    label: ":shipit: Deploy"
    if: "build.tag!=null"
    depends_on: should-deploy
    command: ".buildkite/deploy.sh"
    env:
      EMS_ENVIRONMENT: "production"
    notify:
      - slack:
          channels:
            - "#maps-ops"
          message: "@here EMS File Service production pipeline has run 👀"
