agents:
  image: "docker.elastic.co/ci-agent-images/ems/buildkite-agent-node22:0.5@sha256:b14dcc6455b0678a5f76108ddabbb5c9f1455c8fc4445b03e31e7dc0f12a025d"
  cpu: "2"
  memory: "2G"

steps:
  - key: test
    label: ":hammer_and_wrench: Test"
    commands:
      - "yarn install"
      - "yarn lint"
      - "yarn test"
    retry:
      automatic: true
    agents:
      image: "docker.elastic.co/ci-agent-images/ems/buildkite-agent-node20:0.5@sha256:01d63c1c1e9895e410a8b50c0eb0ce8e986c354085a11ed1d00355a12935ac5e"
      cpu: "4"
      memory: "4G"

  - key: deploy-development
    label: ":rocket: Development"
    branches: "feature-layers"
    depends_on: test
    command: ".buildkite/deploy.sh"
    env:
      EMS_ENVIRONMENT: "development"

  - key: deploy-staging
    label: ":rocket: Staging"
    branches: "master"
    depends_on: test
    command: ".buildkite/deploy.sh"
    env:
      EMS_ENVIRONMENT: "staging"

  - key: should-deploy
    block: ":one-does-not-simply: Deploy"
    if: "build.tag!=null"
    depends_on: test

  - key: deploy-production
    label: ":shipit: Deploy"
    if: "build.tag!=null"
    depends_on: should-deploy
    command: ".buildkite/deploy.sh"
    env:
      EMS_ENVIRONMENT: "production"
    notify:
      - slack:
          channels:
            - "#maps-ops"
          message: "@here EMS File Service production pipeline has run 👀"
