agents:
  image: "docker.elastic.co/ci-agent-images/ems/buildkite-agent:latest"

steps:
  - key: test
    label: ":hammer_and_wrench: Test"
    commands: 
      - "yarn install"
      - "yarn test"

  - key: deploy-development
    label: ":rocket: Deploy to the development environment"
    branches: "feature-layers"
    depends_on: test
    command: ".buildkite/deploy.sh"
    env:
      EMS_ENVIRONMENT: "development"

  - key: deploy-staging
    label: ":rocket: Deploy to the staging environment"
    branches: "master"
    depends_on: test
    command: ".buildkite/deploy.sh"
    env:
      EMS_ENVIRONMENT: "staging"

  - key: should-deploy
    block: ":one-does-not-simply: Deploy to production?"
    if: "build.tag!=null"
    depends_on: test

  - key: deploy-production
    label: ":rocket: Deploy to the production environment"
    if: "build.tag!=null"
    depends_on: should-deploy
    command: ".buildkite/deploy.sh"
    env:
      EMS_ENVIRONMENT: "production"
